/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                /** @enum {string} */
                                status?: "healthy";
                                version?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuración pública (branding, CTA, planes) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["AppSettings"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ejecuta una auditoría (o devuelve la cacheada si existe)
         * @description Rate-limited por IP. Si hay cache <24h y `forceRefresh` no es true, devuelve el resultado cacheado.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuditRequest"];
                };
            };
            responses: {
                /** @description Auditoría completa */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["AuditResult"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                413: components["responses"]["BadRequest"];
                422: components["responses"]["BadRequest"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-status.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera una auditoría guardada por ID */
        get: {
            parameters: {
                query: {
                    /** @description UUID de la auditoría */
                    id: components["parameters"]["AuditId"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["AuditResult"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compare.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compara dos auditorías lado a lado */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uri */
                        url1: string;
                        /** Format: uri */
                        url2: string;
                    };
                };
            };
            responses: {
                /** @description Dos AuditResult y una comparativa */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                audit1?: components["schemas"]["AuditResult"];
                                audit2?: components["schemas"]["AuditResult"];
                                comparison?: {
                                    /** @description id del audit ganador */
                                    winner?: string;
                                    scoreDifference?: number;
                                    moduleComparison?: {
                                        moduleId?: string;
                                        audit1Score?: number;
                                        audit2Score?: number;
                                    }[];
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historial de auditorías para un dominio (hasta 12) */
        get: {
            parameters: {
                query: {
                    /** @description Dominio (sin esquema) */
                    domain: components["parameters"]["Domain"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                domain?: string;
                                totalAudits?: number;
                                /** @enum {string} */
                                trend?: "improving" | "declining" | "stable" | "insufficient_data";
                                history?: {
                                    id?: string;
                                    globalScore?: number;
                                    globalLevel?: components["schemas"]["SemaphoreLevel"];
                                    moduleScores?: {
                                        [key: string]: number;
                                    };
                                    /** Format: date-time */
                                    createdAt?: string;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/login.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autenticación admin
         * @description Rate-limited a 5 intentos por IP en ventana de 15 minutos.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Sesión iniciada. Guarda `data.csrfToken` para mutaciones futuras. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                /** @enum {boolean} */
                                authenticated?: true;
                                csrfToken?: string;
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/logout.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cerrar sesión */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/session.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verifica sesión activa y devuelve CSRF token si autenticado */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                authenticated?: boolean;
                                csrfToken?: string | null;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Métricas agregadas para el dashboard */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["DashboardStats"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/leads.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de leads/auditorías (paginada, filtrable) */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    filter?: "all" | "with_contact" | "critical_score" | "this_week";
                    sort?: "date_desc" | "date_asc" | "score_desc" | "score_asc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                leads?: components["schemas"]["LeadSummary"][];
                                total?: number;
                                page?: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Eliminar una auditoría */
        delete: {
            parameters: {
                query: {
                    /** @description UUID de la auditoría */
                    id: components["parameters"]["AuditId"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
                403: components["responses"]["CsrfInvalid"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/lead-detail.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auditoría completa + datos del lead */
        get: {
            parameters: {
                query: {
                    /** @description UUID de la auditoría */
                    id: components["parameters"]["AuditId"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["AuditResult"] & {
                                leadName?: string | null;
                                leadEmail?: string | null;
                                leadWhatsapp?: string | null;
                                leadCompany?: string | null;
                                /** Format: date-time */
                                createdAt?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settings.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lee la configuración completa */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["AppSettings"];
                        };
                    };
                };
            };
        };
        /**
         * Actualiza settings (merge parcial)
         * @description Acepta cualquier subset de las claves de AppSettings. Las claves en
         *     camelCase se convierten a snake_case automáticamente antes de guardar
         *     en la tabla `settings`. La clave especial `adminPassword` se hashea.
         *     `smtpPassword` igual a `""` o `"••••••••"` se ignora (placeholder).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AppSettings"] & {
                        /** Format: password */
                        adminPassword?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
                403: components["responses"]["CsrfInvalid"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/vulnerabilities.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de vulnerabilidades (paginada) */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                vulnerabilities?: components["schemas"]["VulnerabilityEntry"][];
                                total?: number;
                            };
                        };
                    };
                };
            };
        };
        /** Actualizar vulnerabilidad */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VulnerabilityEntry"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
            };
        };
        /** Crear vulnerabilidad */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VulnerabilityEntry"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                id?: number;
                            };
                        };
                    };
                };
            };
        };
        /** Eliminar vulnerabilidad */
        delete: {
            parameters: {
                query: {
                    id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/update-vulnerabilities.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresca vulnerabilidades desde WPVulnerability.net */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Estadísticas del update */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                newVulnerabilities?: number;
                                updatedVulnerabilities?: number;
                                pluginsChecked?: number;
                                errors?: number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/checklist.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Checklist de correcciones para una auditoría */
        get: {
            parameters: {
                query: {
                    audit_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                metric_id?: string;
                                /** @enum {integer} */
                                completed?: 0 | 1;
                                notes?: string | null;
                                /** Format: date-time */
                                completed_at?: string | null;
                            }[];
                        };
                    };
                };
            };
        };
        /** Toggle un item del checklist */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        auditId: string;
                        metricId: string;
                        completed: boolean;
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/waterfall.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datos de waterfall + CrUX + Lighthouse + resource breakdown */
        get: {
            parameters: {
                query: {
                    /** @description UUID de la auditoría */
                    id: components["parameters"]["AuditId"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK (schemas internos — ver WaterfallPage.tsx) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/snapshot.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot wp-snapshot guardado para una auditoría */
        get: {
            parameters: {
                query: {
                    audit_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK o null si no hay snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                [key: string]: unknown;
                            } | null;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Sube un snapshot (URL de share o JSON directo) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        auditId: string;
                        /** @enum {string} */
                        source: "url" | "upload";
                        shareUrl?: string;
                        /** @description Acepta string (JSON) u objeto */
                        jsonData?: string | {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description OK — incluye reaudit si se regeneró */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                ok?: boolean;
                                analysis?: {
                                    [key: string]: unknown;
                                };
                                reaudit?: boolean;
                                newScore?: number | null;
                                generatedAt?: string | null;
                                siteName?: string | null;
                            };
                        };
                    };
                };
                403: components["responses"]["CsrfInvalid"];
                413: components["responses"]["BadRequest"];
                422: components["responses"]["BadRequest"];
            };
        };
        /** Elimina el snapshot asociado a una auditoría */
        delete: {
            parameters: {
                query: {
                    audit_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/export-leads.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exporta leads a CSV */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Archivo CSV */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/test-email.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Envía un email de prueba con la configuración SMTP actual */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: email */
                        to?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessEnvelope: {
            /** @enum {boolean} */
            success: true;
            data?: unknown;
        };
        ErrorEnvelope: {
            /** @enum {boolean} */
            success: false;
            error: string;
            details?: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        SemaphoreLevel: "critical" | "warning" | "good" | "excellent" | "info" | "unknown";
        MetricResult: {
            id: string;
            name: string;
            /** @description Valor crudo detectado */
            value: string | number | boolean | null;
            displayValue: string;
            score: number | null;
            level: components["schemas"]["SemaphoreLevel"];
            description: string;
            recommendation: string;
            imaginaSolution: string;
            details?: {
                [key: string]: unknown;
            };
        };
        ModuleResult: {
            /** @description wordpress | security | performance | seo | mobile | infrastructure | conversion | page_health | wp_internal */
            id: string;
            name: string;
            /** @description Nombre de icono Lucide */
            icon: string;
            score: number | null;
            level: components["schemas"]["SemaphoreLevel"];
            /** Format: float */
            weight: number;
            metrics: components["schemas"]["MetricResult"][];
            summary: string;
            salesMessage: string;
        };
        SolutionItem: {
            problem: string;
            level: components["schemas"]["SemaphoreLevel"];
            solution: string;
            /** @description Basic | Pro | Custom */
            includedInPlan: string;
        };
        HostingInfo: {
            ip?: string | null;
            provider?: string | null;
            country?: string | null;
            city?: string | null;
            reverseDns?: string | null;
            nameservers?: string[];
        } | null;
        DomainInfo: {
            domain?: string | null;
            registrar?: string | null;
            createdDate?: string | null;
            expiryDate?: string | null;
            daysUntilExpiry?: number | null;
        } | null;
        TechStack: {
            server?: string | null;
            cms?: string | null;
            pageBuilder?: string[];
            ecommerce?: string[];
            cachePlugin?: string[];
            seoPlugin?: string[];
            securityPlugin?: string[];
            jsLibraries?: string[];
            cssFramework?: string[];
            fonts?: string[];
            cdn?: string | null;
            analytics?: string[];
            phpVersion?: string | null;
            httpProtocol?: string | null;
            hostingInfo?: components["schemas"]["HostingInfo"];
            domainInfo?: components["schemas"]["DomainInfo"];
        };
        AuditResult: {
            /** Format: uuid */
            id: string;
            /** Format: uri */
            url: string;
            domain: string;
            /** Format: date-time */
            timestamp: string;
            scanDurationMs: number;
            globalScore: number;
            globalLevel: components["schemas"]["SemaphoreLevel"];
            totalIssues: {
                critical: number;
                warning: number;
                good: number;
            };
            modules: components["schemas"]["ModuleResult"][];
            isWordPress: boolean;
            economicImpact: {
                estimatedMonthlyLoss: number;
                currency: string;
                explanation: string;
            };
            solutionMap: components["schemas"]["SolutionItem"][];
            techStack?: components["schemas"]["TechStack"];
        };
        AuditRequest: {
            /** Format: uri */
            url: string;
            leadName?: string;
            /** Format: email */
            leadEmail?: string;
            leadWhatsapp?: string;
            leadCompany?: string;
            /** @default false */
            forceRefresh: boolean;
        };
        LeadSummary: {
            id: string;
            url: string;
            domain: string;
            leadName?: string | null;
            leadEmail?: string | null;
            leadWhatsapp?: string | null;
            leadCompany?: string | null;
            globalScore: number;
            globalLevel: components["schemas"]["SemaphoreLevel"];
            /** Format: date-time */
            timestamp: string;
            hasContactInfo: boolean;
        };
        DashboardStats: {
            totalAudits: number;
            totalLeads: number;
            auditsToday: number;
            auditsThisWeek: number;
            auditsThisMonth: number;
            averageScore: number;
            scoreDistribution: {
                critical?: number;
                deficient?: number;
                regular?: number;
                good?: number;
                excellent?: number;
            };
            recentAudits: components["schemas"]["LeadSummary"][];
            recurringDomains?: {
                domain?: string;
                totalAudits?: number;
                bestScore?: number;
                worstScore?: number;
                lastAuditId?: string;
                /** @enum {string} */
                trend?: "improving" | "declining" | "stable";
            }[];
        };
        Plan: {
            name: string;
            price: string;
            currency: string;
        };
        AppSettings: {
            companyName?: string;
            companyUrl?: string;
            companyWhatsapp?: string;
            companyEmail?: string;
            companyPlansUrl?: string;
            logoUrl?: string;
            googlePagespeedApiKey?: string;
            leadNotificationEmail?: string;
            smtpHost?: string;
            smtpPort?: number;
            smtpUsername?: string;
            /** @description Vacío o placeholder "••••••••" si existe */
            smtpPassword?: string;
            /** @enum {string} */
            smtpEncryption?: "tls" | "ssl" | "";
            smtpFromEmail?: string;
            smtpFromName?: string;
            rateLimitMaxPerHour?: number;
            cacheTtlHours?: number;
            /** @description Lista separada por comas de orígenes permitidos en /api/admin/* */
            allowedOrigins?: string;
            /** @description Map de moduleId → peso (deben sumar 1.0) */
            moduleWeights?: {
                [key: string]: number;
            };
            thresholds?: {
                excellent?: number;
                good?: number;
                warning?: number;
                critical?: number;
            };
            salesMessages?: {
                [key: string]: string;
            };
            ctaTitle?: string;
            ctaDescription?: string;
            ctaButtonWhatsappText?: string;
            ctaButtonPlansText?: string;
            plans?: components["schemas"]["Plan"][];
        };
        VulnerabilityEntry: {
            id?: number;
            pluginSlug: string;
            pluginName: string;
            affectedVersions: string;
            /** @enum {string} */
            severity: "low" | "medium" | "high" | "critical";
            cveId?: string;
            description: string;
            fixedInVersion?: string;
            /** Format: date-time */
            dateAdded?: string;
        };
    };
    responses: {
        /** @description Sesión ausente o expirada */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Token CSRF ausente o inválido */
        CsrfInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Parámetros inválidos */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Recurso no encontrado */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Demasiadas peticiones */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description UUID de la auditoría */
        AuditId: string;
        /** @description Dominio (sin esquema) */
        Domain: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
